
# Pages CMS config for your Astro repo (GitHub only; no local servers)

media:
  input: src/assets/images
  output: /src/assets/images

content:
  # Blog posts in src/pages/posts
  - name: posts
    label: Posts
    type: collection
    path: "src/pages/posts"
    view:
      fields: [title, date]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: body
        label: Body
        type: rich-text

  # Standalone pages (About, Contact, etc.)
  - name: pages
    label: Pages
    type: collection
    path: "src/pages"
    glob: "*.{md,mdx,astro}"
    view:
      fields: [title]
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text

